services:
  postgres:
    image: postgres:18.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=deposito
      - POSTGRES_USER=deposito
      - POSTGRES_DB=deposito
    volumes:
      - deposit-postgres-data:/var/lib/postgresql/data

volumes:
  deposit-postgres-data:
