spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://localhost/deposito}
spring.datasource.username=${POSTGRES_USER:deposito}
spring.datasource.password=${POSTGRES_PASS:deposito}
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/postgres/schema.sql
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
